services:
  - type: web
    name: stock-market-indices
    rootDirectory: stock-market-indices-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd visualizations && gunicorn app:server
    plan: free
