services:
  - type: web
    name: stock-market-indices
    rootDirectory: stock-market-indices-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir visualizations --bind 0.0.0.0:10000 app:server
    plan: free
